### ISSUE TITLE
Documentation not clear about using s1506

### ISSUE THREAD

**Issue by pik314** [SINTEF-Geometry/SISL#24]
I am trying to use s1506 to compute position, first and second derivatives of a NURBS surface. I have a hard time understanding what is in the eder array output when ider > 0. I have a 2d NURBS in a 3d space. When ider = 0 I am getting three entries per point, which are the coordinates (position) of the NURBS surface. When ider = 1 there are 9 entries per point. The first three are the same as when ider=0. The documentation states that in this case (ider = 1) "position and first derivative" (! note the singular, I think this should be plural "derivatives") are calculated. In my case there should be just two first order derivatives. I can identify eder[3] and eder[7] as the total span in u- and v-directions, but the other entries are unclear. Are eder[5] and eder[8] the first order derivatives? Their values don't look right in my case. Things get even more confusing when ider=2. I am getting 18 entries per point. the first nine are the same as when ider = 1. What are the other 9? 
I think the documentation needs to be a little more specific about this. An annotated example would be great.

**Comment by VibekeSkytt** [comment]
Since the NURBS surface is in 3D space there will be three entries per point or derivative. For ider=1 you will get position, first derivative in u-direction and first derivative in v-direction, all entries represented by 3 doubles. For ider=2, you get position, first derivative in u-direction, first derivative in v-direction, second derivative in u-direction, mixed second derivative and second derivative in v-direction.

**Comment by pik314** [comment]
I see now that derivatives are actually vectors and their components are inserted into the eder array. Thank you.
